# MACROPAD Hotkeys: Windows Embedded-C things
# BRECHTVE 21/06/2022

from adafruit_macropad import keycodes as Kc # REQUIRED if using Kc.* values

app = {                              # REQUIRED dict, must be named 'app'
    'name' : 'Embedded C       1/2', # Application name (<20 chars)
    'macros' : [                     # List of button macros...
        # COLOR    LABEL (<7 chars)    KEY SEQUENCE
        # 1st row ----------
        (0x200000, 'temp.h', [
            '/***************************************************************************//**\n',
            '@file\ttemplate.h\n',
            '@brief\tTemplate functionality.\n',
            '@date\t05/05/2022\n',
            '@version\t1.0\n',
            '@author\tBrecht Van Eeckhoudt (Dekimo)\n',
            '\n',
            '*****************************************************************************\n',
            '\n',
            '@section Versions\n',
            '\n',
            '  @li v1.0: Initial version.\n',
            '\n',
            Kc.BACKSPACE, -Kc.BACKSPACE, Kc.BACKSPACE, -Kc.BACKSPACE,
            '*****************************************************************************\n',
            '\n',
            '@todo\n',
            '  **Future improvements:**@n\n',
            '  - None.\n',
            '\n',
            Kc.BACKSPACE, -Kc.BACKSPACE, Kc.BACKSPACE, -Kc.BACKSPACE,
            Kc.BACKSPACE, -Kc.BACKSPACE, Kc.BACKSPACE, -Kc.BACKSPACE,
            Kc.BACKSPACE, -Kc.BACKSPACE,
            '*****************************************************************************/\n',
            '\n',
            '\n',
            Kc.DELETE, -Kc.DELETE, Kc.DELETE, -Kc.DELETE,
            Kc.DELETE, -Kc.DELETE, Kc.DELETE, -Kc.DELETE
        ]),
		(0x200000, 'temp.h', [
            '/* Include guards prevent multiple inclusions of the same header */\n',
            '#ifndef _TEMPLATE_H_\n',
            '#define _TEMPLATE_H_\n',
            '\n',
            '\n',
            '/* Includes necessary for this header file -----------------------------------*/\n',
            '//#include <stdint.h> /* (u)intXX_t */\n',
            '\n',
            '\n',
            '/* Public definitions --------------------------------------------------------*/\n',
            '// None\n',
            '\n',
            '\n',
            '/* Public prototypes ---------------------------------------------------------*/\n',
            'void template_init (void);\n',
            '\n',
            '\n',
            '#endif /* _TEMPLATE_H_ */\n'
        ]),
        (0x200020, 'cEnum', [
            'typedef enum\n',
            '{\n',
            'Thing1, Thing2, Thing3\n',
            Kc.BACKSPACE, -Kc.BACKSPACE,
            '} template_customType_t;',
            Kc.DELETE, -Kc.DELETE, Kc.DELETE, -Kc.DELETE,
            Kc.DELETE, -Kc.DELETE, Kc.DELETE, -Kc.DELETE
        ]),
        # 2nd row ----------
        (0x200000, 'temp.c', [
            '/***************************************************************************//**\n',
            '@file\ttemplate.c\n',
            '@brief\tTemplate functionality.\n',
            '@date\t05/05/2022\n',
            '@version\t1.0\n',
            '@author\tBrecht Van Eeckhoudt (Dekimo)\n',
            '\n',
            '*****************************************************************************\n',
            '\n',
            '@section Versions\n',
            '\n',
            '  @li v1.0: Initial version.\n',
            '\n',
            Kc.BACKSPACE, -Kc.BACKSPACE, Kc.BACKSPACE, -Kc.BACKSPACE,
            '*****************************************************************************\n',
            '\n',
            '@todo\n',
            '  **Future improvements:**@n\n',
            '  - None.\n',
            '\n',
            Kc.BACKSPACE, -Kc.BACKSPACE, Kc.BACKSPACE, -Kc.BACKSPACE,
            Kc.BACKSPACE, -Kc.BACKSPACE, Kc.BACKSPACE, -Kc.BACKSPACE,
            Kc.BACKSPACE, -Kc.BACKSPACE,
            '*****************************************************************************/\n',
            '\n',
            '\n',
            Kc.DELETE, -Kc.DELETE, Kc.DELETE, -Kc.DELETE,
            Kc.DELETE, -Kc.DELETE, Kc.DELETE, -Kc.DELETE
        ]),
		(0x200000, 'temp.c', [
            '#include "template.h" /* Include corresponding header file */\n',
            '\n',
            '//#include <stdint.h> /* (u)intXX_t */\n',
            '\n',
            '\n',
            '/* Local definitions ---------------------------------------------------------*/\n',
            '// None\n',
            '\n',
            '\n',
            '/* Local variables -----------------------------------------------------------*/\n',
            '// None\n',
            '\n',
            '\n',
            '/* Local prototypes ----------------------------------------------------------*/\n',
            '// None\n',
            '\n',
            '\n',
            '/* Public functions ----------------------------------------------------------*/\n',
            '\n',
            '/**************************************************************************//**\n',
            '@brief\tFunction to initialize the TEMPLATE peripheral.\n',
            '@details\tThis function configures the pins as well as the TEMPLATE-settings.\n',
            '@author\tBrecht Van Eeckhoudt (Dekimo)\n',
            Kc.BACKSPACE, -Kc.BACKSPACE,
            '****************************************************************************/\n',
            'void template_init (void)\n',
            '{\n',
            Kc.DOWN_ARROW, -Kc.DOWN_ARROW, Kc.DOWN_ARROW, -Kc.DOWN_ARROW,
            Kc.BACKSPACE, -Kc.BACKSPACE, Kc.BACKSPACE, -Kc.BACKSPACE,
            Kc.BACKSPACE, -Kc.BACKSPACE, Kc.BACKSPACE, -Kc.BACKSPACE,
            '\n',
            '\n',
            '\n',
            '/* Local functions -----------------------------------------------------------*/\n',
            '\n',
            '// None\n'
        ]),
        (0x200020, 'SwCase', [
            'switch (template)\n',
            '{\n',
            'case constant1:\n',
            '/* Statements */\n',
            'break;\n',
            Kc.BACKSPACE, -Kc.BACKSPACE,
            '\n',
            'case constant2:\n',
            '/* Statements */\n',
            'break;\n',
            Kc.BACKSPACE, -Kc.BACKSPACE,
            '\n',
            'case sameAsDefault:\n',
            'default:\n',
            '/* Statements */'
        ]),
        # 3rd row ----------
        (0x002020, 'Doxgen', [
            '/**************************************************************************//**\n',
            '@brief\tFunction to initialize the TEMPLATE peripheral.\n',
            '@details\tThis function configures the pins as well as the TEMPLATE-settings.\n',
            '@author\tBrecht Van Eeckhoudt (Dekimo)\n',
            Kc.BACKSPACE, -Kc.BACKSPACE,
            '****************************************************************************/',
            Kc.DELETE, -Kc.DELETE, Kc.DELETE, -Kc.DELETE,
            Kc.DELETE, -Kc.DELETE, Kc.DELETE, -Kc.DELETE
        ]),
        (0x002020, 'IntDox', [
            '/** @addtogroup handlers Interrupt Handlers\n',
            ' @{',
            Kc.DELETE, -Kc.DELETE,
            ' */\n',
            '/**************************************************************************//**\n',
            '@brief\tTEMPLATE interrupt handler.\n',
            '@note\tThe *weak* definition for this method is located in `system_efm32hg.h`.\n',
            '@author\tBrecht Van Eeckhoudt (Dekimo)\n',
            Kc.BACKSPACE, -Kc.BACKSPACE,
            '****************************************************************************/\n',
            '\n',
            '/** @} End of Doxygen "handlers" group */',
            Kc.DELETE, -Kc.DELETE, Kc.DELETE, -Kc.DELETE
        ]),
		(0x002020, 'StaDox', ['@note\tThis is a `static` method because it\'s only locally used in this file.']),
        # 4th row ----------
		(0x202000, 'incRTT', ['#include \"SEGGER_RTT.h\" /* Include Segger RTT functionality */']),
        (0x202000, 'String', ['SEGGER_RTT_WriteString(0, \"Template\\r\\n\");']),
		(0x202000, 'uValue', ['SEGGER_RTT_printf(0, \"uValue = %u\\r\\n", uValue);']),
        # Encoder button ---
        (0x000000, '',       [])
    ]
}
